apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitlab
  name: gitlab
spec:
  ports:
  - name: https
    port: 4443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 4080
    protocol: TCP
    targetPort: 80
  - name: ssh
    port: 4022
    protocol: TCP
    targetPort: 22
  selector:
    app: gitlab
  type: LoadBalancer
status:
  loadBalancer: {}
