apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ConfigMap.yml              
  - persistentVolume.yml  
  - Secret.yml   
  - StatefulSet.yml
  - persistentVolumeClaim.yml  
  - sc.yml                
  - Service.yml
