apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: default
spec:
  serviceName: mongo
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
      - name: mongodb
        image: docker.io/mongo:4.2
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongoadmin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "secret"
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all --oplogSize 128 "]
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      storageClassName: "mongodb-storageclass"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
