apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rocketchat-server
  name: rocketchat-server
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rocketchat
  type: LoadBalancer
status:
  loadBalancer: {}
