apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rocketchat
  name: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rocketchat
    spec:
      containers:
      - image: rocket.chat
        name: rocket-chat
        ports:
        - containerPort: 3000
        resources: {}
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-replica-0.mongo:27017/rocketchat
        - name: MONGO_OPLOG_URL
          value: mongodb://mongodb-replica-0.mongo:27017/local
status: {}
